services:
  db:
    image: postgres:16.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_rails_development
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  api:
    build: ./apps/api
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    volumes:
      - ./apps/api:/rails
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: dev_rails_development
    depends_on:
      - db
